name: "Repo Lint"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
           xcode-version: 15.2
      - name: Repo Lint
        run: pod repo lint --verbose .
      - name: Add Repo to Sources
        run: |
          pod repo add self "file://${PWD}" "${{ github.ref_name }}"
      - name: Spec Lint
        run: |
          find Specs -name "*.podspec" -type f | while read -r podspec; do
            echo "::group::Linting $podspec"
            pod spec lint "$podspec" --allow-warnings --verbose --sources=self
            echo "::endgroup::"
          done
